// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRBEp5jyck9VsJBM42E1HO-JvA1AhwQSw',
    appId: '1:806341337510:web:9027eaf0ddf9f1d318ef67',
    messagingSenderId: '806341337510',
    projectId: 'foodapp-c2836',
    authDomain: 'foodapp-c2836.firebaseapp.com',
    storageBucket: 'foodapp-c2836.appspot.com',
    measurementId: 'G-8RC1LCQFSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwc1A9sxFFjvLdyHCfrmOdGqbdkH1pj4A',
    appId: '1:806341337510:android:6248f6bc3a047fa318ef67',
    messagingSenderId: '806341337510',
    projectId: 'foodapp-c2836',
    storageBucket: 'foodapp-c2836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVpN1pWaMwAPW2XYqCEuohxCOyuNxhFiE',
    appId: '1:806341337510:ios:a4e740aa042a325c18ef67',
    messagingSenderId: '806341337510',
    projectId: 'foodapp-c2836',
    storageBucket: 'foodapp-c2836.appspot.com',
    iosBundleId: 'com.example.recipeHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVpN1pWaMwAPW2XYqCEuohxCOyuNxhFiE',
    appId: '1:806341337510:ios:a4e740aa042a325c18ef67',
    messagingSenderId: '806341337510',
    projectId: 'foodapp-c2836',
    storageBucket: 'foodapp-c2836.appspot.com',
    iosBundleId: 'com.example.recipeHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRBEp5jyck9VsJBM42E1HO-JvA1AhwQSw',
    appId: '1:806341337510:web:dae13fb1b541312c18ef67',
    messagingSenderId: '806341337510',
    projectId: 'foodapp-c2836',
    authDomain: 'foodapp-c2836.firebaseapp.com',
    storageBucket: 'foodapp-c2836.appspot.com',
    measurementId: 'G-EYXYCFGST8',
  );
}
